definitions:
  internal_server.CreateTaskRequest:
    properties:
      due_date:
        example: "2025-03-30T12:00:00Z"
        type: string
      payload:
        example: Example payload
        type: string
      title:
        example: Complete project
        type: string
    required:
    - title
    type: object
  internal_server.CreateUserRequest:
    properties:
      email:
        example: john.doe@example.com
        type: string
      name:
        example: John
        type: string
      password:
        example: password123
        minLength: 6
        type: string
    required:
    - email
    - name
    - password
    type: object
  internal_server.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: string
    type: object
  internal_server.Message:
    properties:
      message:
        type: string
    type: object
  internal_server.TaskResponse:
    properties:
      created_at:
        example: "2025-03-25T12:00:00Z"
        type: string
      description:
        example: Finish the pending project by Friday
        type: string
      due_date:
        example: "2025-03-30T12:00:00Z"
        type: string
      id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      status:
        example: pending
        type: string
      title:
        example: Complete project
        type: string
      updated_at:
        example: "2025-03-26T12:00:00Z"
        type: string
    type: object
  internal_server.UpdateTaskRequest:
    properties:
      result:
        example: "2025-04-01T12:00:00Z"
        type: string
      status:
        example: completed
        type: string
    type: object
  internal_server.UserLoginRequest:
    properties:
      email:
        example: john.doe@example.com
        type: string
      password:
        example: password123
        type: string
    required:
    - email
    - password
    type: object
  internal_server.UserLoginResponse:
    properties:
      access_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
      access_token_expires_at:
        example: "2025-02-05T13:15:08Z"
        type: string
      refresh_token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        type: string
      refresh_token_expires_at:
        example: "2025-02-06T13:15:08Z"
        type: string
      session_id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      user:
        $ref: '#/definitions/internal_server.UserResponse'
    type: object
  internal_server.UserResponse:
    properties:
      created_at:
        example: "2025-01-01T12:00:00Z"
        type: string
      email:
        example: john.doe@example.com
        type: string
      id:
        example: 123e4567-e89b-12d3-a456-426614174000
        type: string
      name:
        example: John
        type: string
      updated_at:
        example: "2025-01-02T12:00:00Z"
        type: string
    required:
    - name
    type: object
  internal_server.UsersRequest:
    properties:
      pageID:
        example: 1
        minimum: 1
        type: integer
      pageSize:
        example: 10
        minimum: 1
        type: integer
    required:
    - pageID
    - pageSize
    type: object
  internal_server.renewAccessTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  internal_server.renewAccessTokenResponse:
    properties:
      access_token:
        type: string
      access_token_expires_at:
        type: string
    type: object
info:
  contact: {}
  description: API documentation for CheapStores Service
  title: task-manager API
  version: "1.0"
paths:
  /auth/renew:
    post:
      consumes:
      - application/json
      description: Generates a new access token using a valid refresh token
      parameters:
      - description: Refresh Token Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/internal_server.renewAccessTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.renewAccessTokenResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "401":
          description: Unauthorized or Invalid token
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "404":
          description: Session not found
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Renew Access Token
      tags:
      - auth
  /task:
    get:
      consumes:
      - application/json
      description: Get a list of tasks with pagination
      parameters:
      - description: Page Size
        in: query
        name: page_size
        required: true
        type: integer
      - description: Page Number
        in: query
        name: page_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_server.TaskResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Get Tasks
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Create a new task
      parameters:
      - description: Create Task Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_server.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_server.TaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Create Task
      tags:
      - tasks
  /task/{id}:
    get:
      consumes:
      - application/json
      description: Get task by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.TaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Get Task
      tags:
      - tasks
    put:
      consumes:
      - application/json
      description: Update the status of an existing task
      parameters:
      - description: Update Task Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_server.UpdateTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.TaskResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Update Task Status
      tags:
      - tasks
  /user:
    get:
      consumes:
      - application/json
      description: Get a list of users
      parameters:
      - description: User Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_server.UsersRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_server.UserResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Get Users
      tags:
      - users
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Get user by ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Get User
      tags:
      - users
  /user/login:
    post:
      consumes:
      - application/json
      description: Login user with email and password
      parameters:
      - description: User Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_server.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.UserLoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Login User
      tags:
      - users
  /user/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Create User Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_server.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_server.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Register User
      tags:
      - users
swagger: "2.0"
