PRODUCTION: 0
PORT: 8000
ALLOWED_ORIGINS: http://localhost:3000

ACCESS_TOKEN_DURATION: 24h
REFRESH_TOKEN_DURATION: 24h
TOKEN_SECRET: 12345678901234567890123456789012

WEATHER_API_KEY: 05a6b43ec57773ea05e79b3b9280ae33

DB_URL_DEV: postgres://root:manage123@postgres-db:5432/postgres?sslmode=disable
DB_URL: postgres://root:manage123@postgres-db:5432/postgres?sslmode=disable

PGUSER: root
PGPASSWORD: manage123
PGHOST: postgres-db
PGPORT: 5432
PGDATABASE: postgres

RMQ_ADDRESS: amqp://guest:guest@localhost:5672/

IMAGE: postgis/postgis:15-3.4-alpine
GOOSE_DRIVER: postgres
GOOSE_DBSTRING: $(DB_URL_DEV)
GOOSE_MIGRATION_DIR: ./internal/database/migrations/
