app = "task-manager-6x3jxg"
primary_region = "ams"

# API/HTTP Service
[http_service]
  internal_port = 8000
  force_https = true
  processes = ["api"]  
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1  

# Worker Service (TCP-based, no HTTP)
[[services]]
  internal_port = 8001  # Worker service port
  processes = ["worker"]
  protocol = "tcp"

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "15s"

# Process definitions (entrypoints must match your Docker build)
[processes]
  api = "/app/main"      # Your API binary
  worker = "/app/worker" # Your worker binary

# Virtual machine configuration for API
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
  processes = ["api"]

# Virtual machine configuration for Worker
[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048
  processes = ["worker"]

# Optional scaling (uncomment if needed)
[experimental]
  auto_scale = [
    { process = "worker", min = 2, max = 5, cpu_percent = 70 },
    { process = "api", min = 1, max = 2, cpu_percent = 60 }
  ]

