app = "task-manager-6x3jxg"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"  # Recommended for Go apps

[http_service]
  internal_port = 8000
  force_https = true
  processes = ["api"]
  auto_healing = true
  
  # Health checks (API)
  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/health"
    grace_period = "10s"

[processes]
  api = "api/main"
  worker = "worker/main"

[services]
  [[services.ports]]
    handlers = ["http"]
    port = 80
    service = "api"

  [[services.ports]]
    handlers = ["tcp"]
    port = 5000
    service = "worker"

# Worker-specific settings
[services.for_processes.worker]
  protocol = "tcp"  # Workers typically don't need HTTP
  
  # Worker health checks (TCP)
  [[services.for_processes.worker.tcp_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "15s"

# Scaling configuration
[services.concurrency]
  type = "connections"
  hard_limit = 50
  soft_limit = 40

[experimental]
  auto_scale = [
    { process = "worker", min = 2, max = 5, cpu_percent = 70 },
    { process = "api", min = 1, max = 2, cpu_percent = 60 }
  ]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

  # Optional: Different specs for workers
  [[vm.for_processes.worker]]
    memory_mb = 2048  # Workers get 2GB if needed
    cpus = 2

