# fly.toml app configuration file generated for task-manager-6x3jxg on 2025-04-03T07:43:25Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'task-manager-6x3jxg'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  api = "api/main"
  worker = "worker/main"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
