app = "task-manager-6x3jxg"
primary_region = "ams"

[build]
  builder = "paketobuildpacks/builder:base"  # Recommended for Go apps

# API/HTTP Service
[http_service]
  internal_port = 8000
  force_https = true
  processes = ["api"]  # Changed from 'app' to match your process name
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1  # Recommended minimum for production
  
  # Health checks
  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/health"
    grace_period = "10s"

# Worker Service
[[services]]
  internal_port = 8001  # Worker health port
  processes = ["worker"]
  protocol = "tcp"
  
  # TCP health check for worker
  [[services.tcp_checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "15s"

# Process definitions
[processes]
  api = "api/main"      # Your API entrypoint
  worker = "worker/main" # Your worker entrypoint

# Virtual machine configuration
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# Optional: Different VM specs for workers
[[vm.for.processes.worker]]
  memory_mb = 2048  # Workers get 2GB if needed
  cpus = 2

# Optional scaling (uncomment if needed)
[experimental]
  auto_scale = [
    { process = "worker", min = 2, max = 5, cpu_percent = 70 },
    { process = "api", min = 1, max = 2, cpu_percent = 60 }
  ]
