apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-mngt-api
  labels:
    app: task-mngt-api
spec:
  replicas: 2  # Can be increased for scaling
  selector:
    matchLabels:
      app: task-mngt-api
  template:
    metadata:
      labels:
        app: task-mngt-api
    spec:
      containers:
        - name: api
          image: your-dockerhub-username/task-mngt-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: task-mngt-config
            - secretRef:
                name: task-mngt-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: task-mngt-api
spec:
  selector:
    app: task-mngt-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

