apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
data:
  PRODUCTION: "0"
  PORT: "8000"
  RMQ_ADDRESS: "amqp://guest:guest@rabbitmq:5672/"
  DB_URL: "postgresql://root:manage123@postgres-db:5432/postgres?sslmode=disable"
  DB_URL_DEV: "postgresql://root:manage123@postgres-db:5432/postgres?sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
type: Opaque
data:
  PGUSER: cm9vdA==  # base64 of 'root'
  PGPASSWORD: bWFuYWdlMTIz  # base64 of 'manage123'
  PGDATABASE: cG9zdGdyZXM=  # base64 of 'postgres'
  rabbitmq_user: Z3Vlc3Q=  # base64 of 'guest'
  rabbitmq_pass: Z3Vlc3Q=  # base64 of 'guest'

