apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config
data:
  PRODUCTION: "0"
  PORT: "8000"
  RMQ_ADDRESS: "amqp://guest:guest@rabbitmq:5672/"
  DB_URL: "postgresql://root:manage123@postgres-db:5432/postgres?sslmode=disable"
  DB_URL_DEV: "postgresql://root:manage123@postgres-db:5432/postgres?sslmode=disable"
  WEATHER_API_KEY: "05a6b43ec57773ea05e79b3b9280ae33"
  ACCESS_TOKEN_DURATION: "30m"
  REFRESH_TOKEN_DURATION: "24h"
  TOKEN_SECRET: "12345678901234567890123456789012"
  GOOSE_DRIVER: "postgres"
  GOOSE_DBSTRING: "postgresql://neondb_owner:npg_XynbGtSvg60Q@ep-bitter-mud-a5at4adz-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
  GOOSE_MIGRATION_DIR: "./internal/database/migrations/"
---
apiVersion: v1
kind: Secret
metadata:
  name: task-manager-secrets
type: Opaque
data:
  PGUSER: cm9vdA==  # base64 of 'root'
  PGPASSWORD: bWFuYWdlMTIz  # base64 of 'manage123'
  PGDATABASE: cG9zdGdyZXM=  # base64 of 'postgres'
  rabbitmq_user: Z3Vlc3Q=  # base64 of 'guest'
  rabbitmq_pass: Z3Vlc3Q=  # base64 of 'guest'

